title: Wei He
domain: whe.me
url: https://whe.me
image: https://whe.me/assets/images/og.png
tagline: Full Stack Engineer + Solutions Architect + M.B.A.
description: >-
  Hello there, I'm Dr Kimble ğŸ‘‹
  ( "ğŸ‘¨â€ğŸ’» Doctor" | "â˜ï¸ Fugitive" | "ğŸ’¼ One armed man hunter" )

plugins:
  - jekyll-readme-index
  - jekyll-seo-tag
  - github-pages
