title: Wei He
domain: whe.me
url: https://whe.me
image: https://whe.me/assets/images/og.png
tagline: Full Stack Engineer + Solutions Architect + M.B.A.
description: >-
  Hello there, I'm @wei ğŸ‘‹
  ( "ğŸ‘¨â€ğŸ’» Full Stack Engineer" | "â˜ï¸ Solutions Architect Expert" | "ğŸ’¼ M.B.A." )

plugins:
  - jekyll-readme-index
  - jekyll-seo-tag
  - github-pages
